services:
  postgres:
    image: postgres:15
    container_name: paylead_postgres
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: adminpass
      POSTGRES_DB: paylead_db
    ports:
      - "5432:5432"
    volumes:
      - ./init:/docker-entrypoint-initdb.d

  flask_app:
    build:
      context: .
      dockerfile: app/Dockerfile
    container_name: paylead_flask_app
    ports:
      - "5001:5000"
    environment:
      DATABASE_URI: postgresql://admin:adminpass@postgres:5432/paylead_db
    depends_on:
      - postgres
